# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bruins Den' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bruins Den
  pod 'FSCalendar'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod ‘Firebase/Storage’
  pod ‘FirebaseUI/Storage’
  pod ‘Firebase/Messaging’
  pod 'TwitterKit'
  pod 'Alamofire', '~> 4.4'
# pod 'Kanna', '~> 2.1.0'
  pod “DownPicker”
  pod 'skpsmtpmessage'
  pod 'AZDropdownMenu'


end
